"""add parameters to workout_day_exercises

Revision ID: a638a2b62741
Revises: 89beb337c384
Create Date: 2026-03-17 09:26:20.248985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a638a2b62741'
down_revision: Union[str, Sequence[str], None] = '89beb337c384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('workout_day_exercises', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_day_exercises', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
